#!/usr/bin/ruby
# coding: utf-8

require 'erb'
require 'creole'

c = Creole.new()

my_text = <<-EOL
= THE CREOLE TEST CASE

= Top-level heading (1)
== This a test for creole 0.1 (2)
=== This is a Subheading (3)
==== Subsub (4)
===== Subsubsub (5)

The ending equal signs should not be displayed:

= Top-level heading (1) =
== This a test for creole 0.1 (2) ==
=== This is a Subheading (3) ===
==== Subsub (4) ====
===== Subsubsub (5) =====


You can make things **bold** or //italic// or **//both//** or //**both**//.

Character formatting extends across line breaks: **bold,
this is still bold. This line deliberately does not end in star-star.

Not bold. Character formatting does not cross paragraph boundaries.

You can use [[internal links]] or [[http://www.wikicreole.org|external links]],
give the link a [[internal links|different]] name.

Here's another sentence: This wisdom is taken from [[Ward Cunningham's]]
[[http://www.c2.com/doc/wikisym/WikiSym2006.pdf|Presentation at the Wikisym 06]].

Here's a external link without a description: [[http://www.wikicreole.org]]

Be careful that italic links are rendered properly:  //[[http://my.book.example/|My Book Title]]// 

Free links without braces should be rendered as well, like http://www.wikicreole.org/ and http://www.wikicreole.org/users/~example. 

Creole1.0 specifies that http://bar and ftp://bar should not render italic,
something like foo://bar should render as italic.

You can use this to draw a line to separate the page:
----

You can use lists, start it at the first column for now, please...

unnumbered lists are like
* item a
* item b
* **bold item c**

blank space is also permitted before lists like:
  *   item a
 * item b
* item c
 ** item c.a

or you can number them
# [[item 1]]
# item 2
# // italic item 3 //
    ## item 3.1
  ## item 3.2

up to five levels
* 1
** 2
*** 3
**** 4
***** 5

* You can have
multiline list items
* this is a second multiline
list item

You can use nowiki syntax if you would like do stuff like this:

{{{
Guitar Chord C:

||---|---|---|
||-0-|---|---|
||---|---|---|
||---|-0-|---|
||---|---|-0-|
||---|---|---|
}}}

You can also use it inline nowiki {{{ in a sentence }}} like this.

= Escapes =
Normal Link: http://wikicreole.org/ - now same link, but escaped: ~http://wikicreole.org/ 

Normal asterisks: ~**not bold~**

a tilde alone: ~

a tilde escapes itself: ~~xxx

=== Creole 0.2 ===

This should be a flower with the ALT text "this is the Ruby logo" if your wiki supports ALT text on images:

{{http://www.ruby-lang.org/images/logo.gif|here is the Ruby logo}}

=== Creole 0.4 ===

Tables are done like this:

|=header col1|=header col2| 
|col1|col2| 
|you         |can         | 
|also        |align\\ it. | 

You can format an address by simply forcing linebreaks:

My contact dates:\\
Pone: xyz\\
Fax: +45\\
Mobile: abc

=== Creole 0.5 ===

|= Header title               |= Another header title     |
| {{{ //not italic text// }}} | {{{ **not bold text** }}} |
| //italic text//             | **  bold text **          |

=== Creole 1.0 ===

If interwiki links are setup in your wiki, this links to the WikiCreole page about Creole 1.0 test cases: [[WikiCreole:Creole1.0TestCases]].
EOL

out = c.fromString(my_text)

template = ERB.new <<-EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<meta name="Description" content="Information architecture, Web Design, Web Standards." />
<meta name="Keywords" content="falcon, programming" />
<meta http-equiv="Content-Type" content="text/html; charset="utf-8" />
<link rel="stylesheet" href="base.css" type="text/css" media="screen" />

<title>Greole</title>
  
</head>

<body>

  <!-- header starts here -->
  <div id="header"><div id="header-content">  
    
    <h1 id="logo">Ruby Creole</h1>  
    <h2 id="slogan">Creole 1.0 parser in Ruby</h2>      
  
  </div></div>
        
  <!-- content-wrap starts here -->
  <div id="content-wrap"><div id="content">   
  
    <div id="sidebar" >        
          
      <div class="sidebox">
        <h1>Creole Syntax</h1>
      
        <p>One stupid slogan here...</p>    
    
      </div>  
        
    </div>  
  
    <div id="main">    
<!-- BEGIN of doc generated by Creole Ruby -->
<%= out %>
<!-- END of doc generated by Creole Ruby -->
    </div>      
    
  
  <!-- content-wrap ends here -->    
  </div></div>

  <!-- footer starts here -->  
  <div id="footer"><div id="footer-content">
  
    <div class="col float-left">
      <h2>Site Partners</h2>
      <ul>        
        <li><a href="http://www.rubyfrance.org/"><strong>Ruby</strong> - The programming langage</a></li>
      </ul>      
    </div>
    
    <div class="col float-left">
      <h2>Links</h2>
      <ul>        
        <li><a href="http://www.openwebdesign.org/"><strong>openwebdesign.org</strong></a></li>
        <li><a href="http://www.OSWD.org/"><strong>OSWD.org</strong></a></li>
        <li><a href="http://www.zeroweb.org/"><strong>zeroweb.org</strong></a></li>

        <li><a href="http://www.alistapart.com/"><strong>Alistapart</strong></a></li>    
        <li><a href="http://www.cssremix.com/"><strong>CSS Remix</strong></a></li>          
      </ul>      
    </div>    
  
    <div class="col2 float-right">
      <p>
      &copy; copyright 2009 <strong>Kib²</strong><br /> 
      Design by: <a href="index.html"><strong>styleshout</strong></a> &nbsp; &nbsp;<br />

      Valid <a href="http://jigsaw.w3.org/css-validator/check/referer"><strong>CSS</strong></a> | 
            <a href="http://validator.w3.org/check/referer"><strong>XHTML</strong></a>
       <br />
       Contents of this site &copy; Kib².
      </p>
    
    </div>
  
  </div></div>

  <!-- footer ends here -->

</body>
</html>
EOF

File.open('out.html', "w") do |f|
  f << template.result(binding)
end